version: "3"
services:
  frontend-react:
    ports:
      - "3000:3000"
    command: "npm start"

  backend-node:
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    command: "npm run dev"

  backend-flask:
    environment: 
      - FLASK_ENV=development
      - FLASK_RUN_PORT=5001
    ports:
      - "5001:5001"
    command: "gunicorn -w 2 -b 0.0.0.0:5001 app:app --reload"
    