version: "3"
services:
  frontend-react:
    command: "npm run build"

  backend-node:
    environment:
      - NODE_ENV=production
    command: "npm run prod"

  backend-flask:
    environment: 
      - FLASK_ENV=production
    command: "gunicorn -w 2 -b 0.0.0.0:5001 app:app"

  reverse-proxy:
    volumes:
      - ./frontend-react/build:/var/www/app
